# Generated by Django 4.0.5 on 2022-07-16 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animal', '0002_alter_animal_description_alter_animal_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('pk_type_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.typeanimal')),
            ],
            options={
                'db_table': 'vaccine',
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_dose', models.IntegerField(verbose_name='Vaccine Dose')),
                ('batch', models.CharField(max_length=150, verbose_name='Batch')),
                ('date_vaccination', models.DateTimeField(verbose_name='Date Vaccine')),
                ('date_return', models.DateTimeField(verbose_name='Date Return')),
                ('responsible', models.CharField(max_length=150, verbose_name='Responsible')),
                ('fk_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.animal')),
                ('pk_vaccine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vaccination.vaccine')),
            ],
            options={
                'db_table': 'vaccination',
            },
        ),
    ]
