# Generated by Django 4.0.5 on 2022-07-16 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccination',
            old_name='pk_vaccine',
            new_name='fk_vaccine',
        ),
        migrations.RenameField(
            model_name='vaccine',
            old_name='pk_type_animal',
            new_name='fk_type_animal',
        ),
    ]
