# Generated by Django 4.0.5 on 2022-07-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=models.TextField(blank=True, max_length=999, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='photo'),
        ),
    ]
